### ISSUE TITLE
Update for Mythic v2.2 compatibility

### ISSUE THREAD

**Issue by mattreduce** [MythicAgents/venus#33]
Follow instructions in https://docs.mythic-c2.net/v/version-2.2/updating/mythic-2.1-greater-than-2.2-updates/agents-2.1.-greater-than-2.2.2

**Comment by its-a-feature** [comment]
Mythic 2.2 will be merged into master on June 7th, 2021.

**Comment by mattreduce** [comment]
Thanks for the heads-up, @its-a-feature 😄✅
